import MainLayout from "@/components/common/main_layout";
import FeaturedBanner from "@/components/pages/landing/featured-banner";
import FeaturedSlider from "@/components/pages/landing/featured-slider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tech Nexa",
  description: "Generated by create next app",
};

export default function Index() {
  return (
    <>
      <FeaturedBanner />
      <FeaturedSlider />
    </>
  );
}
