import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "@/app/globals.css";
import SubLayout from "@/components/common/sub_layout";

const inter = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SubLayout>{children}</SubLayout>
      </body>
    </html>
  );
}
